# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('coutext', models.TextField()),
                ('author', models.TextField(verbose_name=myblog.models.User)),
            ],
        ),
    ]
